name: porcupine-http
version: 0.1.0.0
synopsis: A location accessor for porcupine to connect to HTTP sources/sinks
description: |
  Gives a porcupine task pipeline access to HTTP urls (GET, POST or
  PUT). Implements a specific location type (represented as JSON object) to pack
  together the url and some common HTTP header fields (method, content-type,
  etc.). See the README at <https://github.com/tweag/porcupine#README.md> and
  the examples in the `porcupine-http` package.
maintainer: Yves Parès <yves.pares@tweag.io>
github: tweag/porcupine
homepage: https://tweag.github.io/porcupine/
category: Data, Arrows, Combinators, Control, Web
copyright: 2018 EURL Tweag, NovaDiscovery

ghc-options: -Wall

dependencies:
  - aeson
  - base >= 4.10 && < 5
  - containers
  - transformers
  - safe-exceptions
  - http-conduit
  - http-client
  - resourcet
  - bytestring
  - mime-types
  - streaming
  - streaming-bytestring
  - conduit
  - streaming-conduit
  - text
  - reader-soup == 0.1.*
  - porcupine-core == 0.1.*

library:
  source-dirs: src

executables:
  example-pokeapi:
    source-dirs: examples/example-Poke
    main: ExamplePokeAPI.hs
    dependencies:
      - porcupine-core
      - porcupine-http
      - docrecords
      - aeson
      - unordered-containers
      - text
      - hvega
  example-stock:
    source-dirs: examples/example-Stock
    main: ExampleStockAPI.hs
    dependencies:
      - porcupine-core
      - porcupine-http
      - docrecords
      - aeson
      - unordered-containers
      - text
      - hvega
